### ISSUE TITLE
Copy the Template

### ISSUE THREAD

**Issue by hariharan-isgec** [hariharan-isgec/odootutorial#1]
@aayushsrivastava see below instructions

1. Create a folder myaddons
2. Create a Folder gmc_module
3. Copy the code repository inside gmc_module
4. Follow the Instruction given in the attached document
[Odoo Module Creation Template.docx](https://github.com/hariharan-isgec/odootutorial/files/3321441/Odoo.Module.Creation.Template.docx)
5. Commit the changes into git repository for my review

**Comment by aayushsrivastava** [comment]
@hariharan-isgec modifications done
module showing in lisiting
![Screenshot](https://i.imgur.com/G3QAXTL.png)
